name: wine-prediction
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png
          
          # Create CML report
          name: Upload failed tests
          if: ${{ failure() }}
          uses: edunad/actions-image@v2.0.0
          with:
              path: './feature_importance/**/*.png'
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              title: 'Failed E2E tests 🙀'
              annotationLevel: 'failure'  
          # cat metrics.txt >> report.md
          # echo '![Model Metric](feature_importance.png "feature_importance")' >> report.md
          # cml comment create report.md
